### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by rsjaq** [chrisgrieser/alfred-atop#2]
### Bug Description

Bluetooth paired devices are not being displayed when typing the keyword "blue".

### Relevant Screenshot

![Screenshot 2023-07-31 at 00 08 28](https://github.com/chrisgrieser/alfred-atop/assets/21664145/d5f91002-57d0-401d-9a5d-7e0fd2ba7e7c)

### Debugging Log

```Text
[00:09:18.420] atop[Script Filter] Queuing argument '(null)'
[00:09:18.773] atop[Script Filter] Script with argv '(null)' finished
[00:09:18.776] ERROR: atop[Script Filter] Code 1: /Users/Username/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.52D64179-E064-42F0-9E3B-AD324CA51432/scripts/bluetooth-devices.js: execution error: Error: TypeError: undefined is not an object (evaluating 'allDevices.device_connected.forEach') (-2700)
```

### Workflow Configuration

![Screenshot 2023-07-31 at 00 10 18](https://github.com/chrisgrieser/alfred-atop/assets/21664145/4297b287-6415-4dfc-b914-276be58d3cbb)

### Checklist

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/alfred-atop/releases/latest) of this workflow.
- [X] I am using Alfred 5. (Older versions are not supported anymore.)

**Comment by chrisgrieser** [comment]
Could you attach a screenshot of your Bluetooth preferenes, where all your devices are listed? (you can blur out the device names, I just need to see the devices and the preferences)

**Comment by rsjaq** [comment]
![Screenshot 2023-07-31 at 00 27 46](https://github.com/chrisgrieser/alfred-atop/assets/21664145/3eaed19e-1e20-4842-abcb-d4d3f652967a)

**Comment by chrisgrieser** [comment]
Ah, I think I see where the problem lies.

Could you open the Terminal and run the following command:

```bash
system_profiler -json SPBluetoothDataType
```
and post here the output of that command?

**Comment by rsjaq** [comment]
023-07-31 11:31:21.027 system_profiler[14232:444263] SystemInfo-AccessoryFW - JBL T450BT: no firmware version info available
2023-07-31 11:31:21.029 system_profiler[14232:444263] SystemInfo-AccessoryFW - Pro: no firmware version info available
2023-07-31 11:31:21.029 system_profiler[14232:444263] SystemInfo-AccessoryFW from dict - SoundCore 2 = 0x011B
{
  "SPBluetoothDataType" : [
    {
      "apple_bluetooth_version" : "8.0.5d7",
      "device_title" : [
        {
          "JBL T450BT" : {
            "device_addr" : "30-C0-1B-E8-3D-AE",
            "device_classOfDevice" : "0x04 0x01 0x240404",
            "device_core_spec" : "4.1",
            "device_isconfigured" : "attrib_Yes",
            "device_isconnected" : "attrib_No",
            "device_ispaired" : "attrib_Yes",
            "device_majorClassOfDevice_string" : "Audio",
            "device_manufacturer" : "Unknown (0x7, 0x13B3)",
            "device_minorClassOfDevice_string" : "Headset",
            "device_services" : "AVRCP CT, A2DP Sink, HandsFree, AVRCP TG, Headset",
            "device_supportsEDR" : "attrib_Yes",
            "device_supportsESCO" : "attrib_Yes",
            "device_supportsSSP" : "attrib_Yes"
          }
        },
        {
          "Pro" : {
            "device_addr" : "26-93-53-39-8E-C9",
            "device_classOfDevice" : "0x04 0x01 0x240404",
            "device_core_spec" : "5.1",
            "device_isconfigured" : "attrib_Yes",
            "device_isconnected" : "attrib_No",
            "device_ispaired" : "attrib_Yes",
            "device_majorClassOfDevice_string" : "Audio",
            "device_minorClassOfDevice_string" : "Headset",
            "device_services" : "JL_A2DP, JL_HFP",
            "device_supportsEDR" : "attrib_Yes",
            "device_supportsESCO" : "attrib_Yes",
            "device_supportsSSP" : "attrib_Yes"
          }
        },
        {
          "SoundCore 2" : {
            "device_addr" : "08-EB-ED-A6-9B-0B",
            "device_classOfDevice" : "0x04 0x01 0x240404",
            "device_core_spec" : "4.2",
            "device_fw_version" : "0x011B",
            "device_isconfigured" : "attrib_Yes",
            "device_isconnected" : "attrib_No",
            "device_ispaired" : "attrib_Yes",
            "device_majorClassOfDevice_string" : "Audio",
            "device_minorClassOfDevice_string" : "Headset",
            "device_productID" : "0x0500",
            "device_services" : "AVRCP CT, A2DP Sink, HandsFree, AVRCP TG",
            "device_supportsEDR" : "attrib_Yes",
            "device_supportsESCO" : "attrib_Yes",
            "device_supportsSSP" : "attrib_Yes",
            "device_vendorID" : "0x099A"
          }
        }
      ],
      "incoming_serial_ports_title" : [
        {
          "Bluetooth-Incoming-Port" : {
            "device_authentication" : "attrib_No",
            "device_channel" : "3"
          }
        }
      ],
      "local_device_title" : {
        "general_address" : "B8-E8-56-34-5F-13",
        "general_autoseek_keyboard" : "attrib_On",
        "general_autoseek_pointing" : "attrib_On",
        "general_chipset" : "20702B0",
        "general_connectable" : "attrib_Yes",
        "general_device_class_composite" : "0x38010C",
        "general_device_class_major" : "0x01",
        "general_device_class_minor" : "0x03",
        "general_discoverable" : "attrib_Off",
        "general_fw_version" : "v150 c9319",
        "general_hardware_transport" : "USB",
        "general_hci_revision" : "0x2467",
        "general_hci_version" : "4.0 (0x6)",
        "general_lmp_subversion" : "0x4196",
        "general_lmp_version" : "4.0 (0x6)",
        "general_mfg" : "Broadcom",
        "general_name" : "MacBook Pro",
        "general_power" : "attrib_On",
        "general_productID" : "0x8289",
        "general_remoteWake" : "attrib_On",
        "general_service_class" : "0x1C0",
        "general_supports_handoff" : "attrib_Yes",
        "general_supports_instantHotspot" : "attrib_Yes",
        "general_supports_lowEnergy" : "attrib_Yes",
        "general_type_complete_string" : "Mac Portable",
        "general_type_major_string" : "Computer",
        "general_vendorID" : "0x05AC"
      },
      "services_title" : [
        {
          "file_browsing_title" : {
            "service_FTPRootFolder" : "~/Public",
            "service_OBEXReceive" : "service_acceptAll",
            "service_state" : "attrib_disabled"
          }
        },
        {
          "object_push_title" : {
            "service_OBEXFolder" : "~/Downloads",
            "service_OBEXHandle_Other" : "service_saveToLocation",
            "service_OBEXReceive" : "service_acceptAll",
            "service_state" : "attrib_disabled"
          }
        },
        {
          "internet_sharing_title" : {
            "service_state" : "attrib_disabled"
          }
        }
      ]
    }
  ]
}%

**Comment by chrisgrieser** [comment]
oh, okay, it looks like on your device, the output of the command looks totally different from mine, which I of course have not accounted for in the workflow.

Could you share your mac device model and your macOS version number?

**Comment by rsjaq** [comment]
macOS Big Sur
Version 11.7.9
MacBook Pro (Retina, 15-inch, Late 2013)

**Comment by chrisgrieser** [comment]
okay, version 1.0.9 should fix the problem: https://github.com/chrisgrieser/alfred-atop/releases/tag/1.0.9

**Comment by rsjaq** [comment]
![Screenshot 2023-07-31 at 13 12 43](https://github.com/chrisgrieser/alfred-atop/assets/21664145/861b953c-52c5-4395-8de0-aaf4455a140d)

Unfortunately, it's still showing an error.

**Comment by chrisgrieser** [comment]
ah, that's actually another problem on top of the existing problem.

Reason, is that my code is using some newer functions which were not yet available on older macOS versions.

I released version 1.0.10, which should avoid using that function: https://github.com/chrisgrieser/alfred-atop/releases/tag/1.0.10

Hopefully that fixes it. If not, I am afraid your macOS version is just too old to be supported, and you should update it if possible

**Comment by rsjaq** [comment]
OK, I installed 1.0.10 and unfortunately, still no joy. And unfortunately for me, my macOS is as up to date as it can be.

Thank you for your time and effort, I really appreciate it.

**Comment by chrisgrieser** [comment]
yeah, too bad! Hope the rest of the features still work fine :(

**Comment by chrisgrieser** [comment]
Oh, I just had an idea. Could you try 1.0.11?

https://github.com/chrisgrieser/alfred-atop/releases/tag/1.0.11

**Comment by rsjaq** [comment]
Yes! It works!

![Screenshot 2023-07-31 at 14 46 38](https://github.com/chrisgrieser/alfred-atop/assets/21664145/d678f408-6bd6-499f-af65-69b2b4b72b28)
![Screenshot 2023-07-31 at 14 46 59](https://github.com/chrisgrieser/alfred-atop/assets/21664145/15059847-e919-4d6e-9465-1744a70e36be)

Well done, excellent job.

"Hope the rest of the features still work fine" - As far as I tried, all the other features work OK.

Thank you again, I appreciate it.
